### ISSUE TITLE
No published way to donate directly on Arbitrum

### ISSUE THREAD

**Issue by chrishobcroft** [protocolguild/documentation#169]
## Summary

First, it would seem that the address published on [the Protocol Guild's "Donate" page](https://protocol-guild.readthedocs.io/en/latest/10-donate.html) is a contract wallet on Mainnet, whose address is receiving funds on Arbitrum, at least [according to Arbiscan](https://arbiscan.io/address/0xF29Ff96aaEa6C9A1fBa851f74737f3c069d4f1a9). I don't know whether those funds are accessible but I hope they might be somehow.

Secondly, it would be worthwhile to be clear about where the Protocol Guild should receive direct donations on Arbitrum, as the Livepeer Community would like to propose a donation to Protocol Guild, from their 255673 LPT Treasury, equivalent to $4.8m at current prices.

[Applications for grants from the treasury can be made here.](https://explorer.livepeer.org/treasury/create-proposal) The community of stake-delegated Orchestrators will deliberate on any grant applications.

## Proposed solution

Make an Account on Arbitrum and publish its address [here](https://protocol-guild.readthedocs.io/en/latest/10-donate.html). this can be used in the "LPT Receiver" field in the [Create Proposal form](https://explorer.livepeer.org/treasury/create-proposal):

![image](https://github.com/protocolguild/documentation/assets/2212651/79c37bef-d978-431b-85e3-464ad0c48333)
Figure 1: The [Create Proposal form](https://explorer.livepeer.org/treasury/create-proposal).

**Comment by tvanepps** [comment]
Hey! We are in the middle of an comprehensive update to the docs, including the latest donation addresses on various L2s. 

> I don't know whether those funds are accessible but I hope they might be somehow.

we are aware of this mishap - right now that vesting address is not deployed on arbitrum, but in theory could be. 

For now, any contributions to PG on Arbitrum can be sent to the multisig at arb1:0x32e3C7fD24e175701A35c224f2238d18439C7dBC. feel free to DM me on other platforms to confirm this, or further discuss an LPT contribution

**Comment by tvanepps** [comment]
Docs update has now been merged, see the Donate page [here](https://protocol-guild.readthedocs.io/en/latest/04-donate.html) with the Arbitrum Multisig
